//
//  UILabel+AOZCategory.h
//  AOZKit
//
//  Auto generated by Aozorany.
//  DO NOT EDIT THIS FILE DIRECTLY, IF YOU HAVE NEW CLASSES OR PROPERTIES, PLEASE ADD THEM TO AOZCategorygGenerator.py!


#import <UIKit/UIKit.h>


@interface UILabel (AOZCategory)

#pragma mark Text Attributes
- (UILabel * (^)(UIColor *))aozTextColor;
- (UILabel * (^)(NSLineBreakMode))aozLineBreakMode;
- (UILabel * (^)(NSString *))aozText;
- (UILabel * (^)(NSAttributedString *))aozAttributedText;
- (UILabel * (^)(UIFont *))aozFont;
- (UILabel * (^)(NSTextAlignment))aozTextAlignment;

#pragma mark Sizing the Label Text
- (UILabel * (^)(NSInteger))aozNumberOfLines;

#pragma mark Highlight Values
- (UILabel * (^)(BOOL))aozHighlighted;
- (UILabel * (^)(UIColor *))aozHighlightedTextColor;

#pragma mark Drawing a Shadow
- (UILabel * (^)(CGSize))aozShadowOffset;
- (UILabel * (^)(UIColor *))aozShadowColor;

#pragma mark Superviews
- (UILabel * (^)(UIView *))aozAddToSuperview;

#pragma mark Layers
- (UILabel * (^)(UIColor *))aozLayerBorderColor;
- (UILabel * (^)(CGFloat))aozLayerBorderWidth;
- (UILabel * (^)(CGFloat))aozLayerCornerRaduis;

#pragma mark Bounds and Frames
- (UILabel * (^)(CGRect))aozFrame;
- (UILabel * (^)(CGAffineTransform))aozTransform;
- (UILabel * (^)(CGRect))aozBounds;
- (UILabel * (^)(CGPoint))aozCenter;

#pragma mark Visual Appearance
- (UILabel * (^)(BOOL))aozClipsToBounds;
- (UILabel * (^)(BOOL))aozOpaque;
- (UILabel * (^)(UIColor *))aozTintColor;
- (UILabel * (^)(UIViewTintAdjustmentMode))aozTintAdjustmentMode;
- (UILabel * (^)(UIColor *))aozBackgroundColor;
- (UILabel * (^)(CGFloat))aozAlpha;
- (UILabel * (^)(BOOL))aozHidden;

#pragma mark Events
- (UILabel * (^)(BOOL))aozUserInteractionEnabled;
- (UILabel * (^)(BOOL))aozExclusiveTouch;
- (UILabel * (^)(BOOL))aozMultipleTouchEnabled;

#pragma mark Resizing Behavior
- (UILabel * (^)(UIViewContentMode))aozContentMode;

#pragma mark Identifying the View at Runtime
- (UILabel * (^)(NSInteger))aozTag;

@end
