//
//  UITableView+AOZCategory.h
//  AOZKit
//
//  Auto generated by Aozorany.
//  DO NOT EDIT THIS FILE DIRECTLY, IF YOU HAVE NEW CLASSES OR PROPERTIES, PLEASE ADD THEM TO AOZCategorygGenerator.py!


#import <UIKit/UIKit.h>


@interface UITableView (AOZCategory)

#pragma mark Delegate And DataSource
- (UITableView * (^)(id<UITableViewDelegate>))aozDelegate;
- (UITableView * (^)(id<UITableViewDataSource>))aozDataSource;

#pragma mark Configuring a Table View
- (UITableView * (^)(CGFloat))aozRowHeight;
- (UITableView * (^)(UITableViewCellSeparatorStyle))aozSeparatorStyle;
- (UITableView * (^)(UIColor *))aozSeparatorColor;
- (UITableView * (^)(UIVisualEffect *))aozSeparatorEffect;
- (UITableView * (^)(UIView *))aozBackgroundView;
- (UITableView * (^)(UIEdgeInsets))aozSeparatorInset;
- (UITableView * (^)(BOOL))aozCellLayoutMarginsFollowReadableWidth;

#pragma mark Header and Footer Views
- (UITableView * (^)(UIView *))aozTableHeaderView;
- (UITableView * (^)(UIView *))aozTableFooterView;
- (UITableView * (^)(CGFloat))aozSectionHeaderHeight;
- (UITableView * (^)(CGFloat))aozSectionFooterHeight;

#pragma mark Estimating Element Heights
- (UITableView * (^)(CGFloat))aozEstimatedRowHeight;
- (UITableView * (^)(CGFloat))aozEstimatedSectionHeaderHeight;
- (UITableView * (^)(CGFloat))aozEstimatedSectionFooterHeight;

#pragma mark Managing Selections
- (UITableView * (^)(BOOL))aozAllowsSelection;
- (UITableView * (^)(BOOL))aozAllowsMultipleSelection;
- (UITableView * (^)(BOOL))aozAllowsSelectionDuringEditing;
- (UITableView * (^)(BOOL))aozAllowsMultipleSelectionDuringEditing;

#pragma mark Editing
- (UITableView * (^)(BOOL))aozEditing;

#pragma mark Table Index
- (UITableView * (^)(NSInteger))aozSectionIndexMinimumDisplayRowCount;
- (UITableView * (^)(UIColor *))aozSectionIndexColor;
- (UITableView * (^)(UIColor *))aozSectionIndexBackgroundColor;
- (UITableView * (^)(UIColor *))aozSectionIndexTrackingBackgroundColor;

#pragma mark Managing Focus
- (UITableView * (^)(BOOL))aozRemembersLastFocusedIndexPath;

#pragma mark Delegate

#pragma mark Display of Content
- (UITableView * (^)(CGPoint))aozContentOffset;
- (UITableView * (^)(CGSize))aozContentSize;
- (UITableView * (^)(UIEdgeInsets))aozContentInset;

#pragma mark Managing Scrolling
- (UITableView * (^)(BOOL))aozScrollEnabled;
- (UITableView * (^)(BOOL))aozDirectionalLockEnabled;
- (UITableView * (^)(BOOL))aozScrollsToTop;
- (UITableView * (^)(BOOL))aozPagingEnabled;
- (UITableView * (^)(BOOL))aozBounces;
- (UITableView * (^)(BOOL))aozAlwaysBounceVertical;
- (UITableView * (^)(BOOL))aozAlwaysBounceHorizontal;
- (UITableView * (^)(BOOL))aozCanCancelContentTouches;
- (UITableView * (^)(BOOL))aozDelaysContentTouches;
- (UITableView * (^)(CGFloat))aozDecelerationRate;

#pragma mark Scroll Indicator 
- (UITableView * (^)(UIScrollViewIndicatorStyle))aozIndicatorStyle;
- (UITableView * (^)(UIEdgeInsets))aozScrollIndicatorInsets;
- (UITableView * (^)(BOOL))aozShowsHorizontalScrollIndicator;
- (UITableView * (^)(BOOL))aozShowsVerticalScrollIndicator;

#pragma mark Zooming and Panning
- (UITableView * (^)(CGFloat))aozZoomScale;
- (UITableView * (^)(CGFloat))aozMaximumZoomScale;
- (UITableView * (^)(CGFloat))aozMinimumZoomScale;
- (UITableView * (^)(BOOL))aozBouncesZoom;

#pragma mark Keyboard and Index
- (UITableView * (^)(UIScrollViewKeyboardDismissMode))aozKeyboardDismissMode;
- (UITableView * (^)(UIScrollViewIndexDisplayMode))aozIndexDisplayMode;

#pragma mark Superviews
- (UITableView * (^)(UIView *))aozAddToSuperview;

#pragma mark Layers
- (UITableView * (^)(CGFloat))aozLayerBorderWidth;
- (UITableView * (^)(UIColor *))aozLayerBorderColor;
- (UITableView * (^)(CGFloat))aozLayerCornerRaduis;

#pragma mark Bounds and Frames
- (UITableView * (^)(CGRect))aozFrame;
- (UITableView * (^)(CGRect))aozBounds;
- (UITableView * (^)(CGPoint))aozCenter;
- (UITableView * (^)(CGAffineTransform))aozTransform;

#pragma mark Visual Appearance
- (UITableView * (^)(UIColor *))aozBackgroundColor;
- (UITableView * (^)(BOOL))aozHidden;
- (UITableView * (^)(CGFloat))aozAlpha;
- (UITableView * (^)(BOOL))aozOpaque;
- (UITableView * (^)(UIColor *))aozTintColor;
- (UITableView * (^)(UIViewTintAdjustmentMode))aozTintAdjustmentMode;
- (UITableView * (^)(BOOL))aozClipsToBounds;

#pragma mark Events
- (UITableView * (^)(BOOL))aozUserInteractionEnabled;
- (UITableView * (^)(BOOL))aozMultipleTouchEnabled;
- (UITableView * (^)(BOOL))aozExclusiveTouch;

#pragma mark Resizing Behavior
- (UITableView * (^)(UIViewContentMode))aozContentMode;

#pragma mark Identifying the View at Runtime
- (UITableView * (^)(NSInteger))aozTag;

@end
