//
//  UITextField+AOZCategory.h
//  AOZKit
//
//  Auto generated by Aozorany.
//  DO NOT EDIT THIS FILE DIRECTLY, IF YOU HAVE NEW CLASSES OR PROPERTIES, PLEASE ADD THEM TO AOZCategorygGenerator.py!


#import <UIKit/UIKit.h>


@interface UITextField (AOZCategory)

#pragma mark Text Attributes
- (UITextField * (^)(NSAttributedString *))aozAttributedPlaceholder;
- (UITextField * (^)(BOOL))aozSecureTextEntry;
- (UITextField * (^)(UIReturnKeyType))aozReturnKeyType;
- (UITextField * (^)(UIFont *))aozFont;
- (UITextField * (^)(NSString *))aozPlaceholder;
- (UITextField * (^)(NSAttributedString *))aozAttributedText;
- (UITextField * (^)(NSDictionary<NSString *,id> *))aozTypingAttributes;
- (UITextField * (^)(NSDictionary<NSString *,id> *))aozDefaultTextAttributes;
- (UITextField * (^)(NSString *))aozText;
- (UITextField * (^)(UIColor *))aozTextColor;
- (UITextField * (^)(NSTextAlignment))aozTextAlignment;

#pragma mark Sizing
- (UITextField * (^)(BOOL))aozAdjustsFontSizeToFitWidth;
- (UITextField * (^)(CGFloat))aozMinimumFontSize;

#pragma mark Editing Behavior
- (UITextField * (^)(BOOL))aozClearsOnBeginEditing;
- (UITextField * (^)(BOOL))aozClearsOnInsertion;
- (UITextField * (^)(BOOL))aozAllowsEditingTextAttributes;

#pragma mark Background Appearance
- (UITextField * (^)(UITextBorderStyle))aozBorderStyle;
- (UITextField * (^)(UIImage *))aozDisabledBackground;
- (UITextField * (^)(UIImage *))aozBackground;

#pragma mark Overlay Views
- (UITextField * (^)(UIView *))aozRightView;
- (UITextField * (^)(UITextFieldViewMode))aozLeftViewMode;
- (UITextField * (^)(UIView *))aozLeftView;
- (UITextField * (^)(UITextFieldViewMode))aozClearButtonMode;
- (UITextField * (^)(UITextFieldViewMode))aozRightViewMode;

#pragma mark Delegate
- (UITextField * (^)(id<UITextFieldDelegate>))aozDelegate;

#pragma mark System Input Views
- (UITextField * (^)(UIView *))aozInputView;
- (UITextField * (^)(UIView *))aozInputAccessoryView;

#pragma mark Superviews
- (UITextField * (^)(UIView *))aozAddToSuperview;

#pragma mark Layers
- (UITextField * (^)(UIColor *))aozLayerBorderColor;
- (UITextField * (^)(CGFloat))aozLayerBorderWidth;
- (UITextField * (^)(CGFloat))aozLayerCornerRaduis;

#pragma mark Bounds and Frames
- (UITextField * (^)(CGRect))aozFrame;
- (UITextField * (^)(CGAffineTransform))aozTransform;
- (UITextField * (^)(CGRect))aozBounds;
- (UITextField * (^)(CGPoint))aozCenter;

#pragma mark Visual Appearance
- (UITextField * (^)(BOOL))aozClipsToBounds;
- (UITextField * (^)(BOOL))aozOpaque;
- (UITextField * (^)(UIColor *))aozTintColor;
- (UITextField * (^)(UIViewTintAdjustmentMode))aozTintAdjustmentMode;
- (UITextField * (^)(UIColor *))aozBackgroundColor;
- (UITextField * (^)(CGFloat))aozAlpha;
- (UITextField * (^)(BOOL))aozHidden;

#pragma mark Events
- (UITextField * (^)(BOOL))aozUserInteractionEnabled;
- (UITextField * (^)(BOOL))aozExclusiveTouch;
- (UITextField * (^)(BOOL))aozMultipleTouchEnabled;

#pragma mark Resizing Behavior
- (UITextField * (^)(UIViewContentMode))aozContentMode;

#pragma mark Identifying the View at Runtime
- (UITextField * (^)(NSInteger))aozTag;

@end
