//
//  UITextView+AOZCategory.h
//  AOZKit
//
//  Auto generated by Aozorany.
//  DO NOT EDIT THIS FILE DIRECTLY, IF YOU HAVE NEW CLASSES OR PROPERTIES, PLEASE ADD THEM TO AOZCategorygGenerator.py!


#import <UIKit/UIKit.h>


@interface UITextView (AOZCategory)

#pragma mark Text Attributes
- (UITextView * (^)(NSString *))aozText;
- (UITextView * (^)(BOOL))aozEditable;
- (UITextView * (^)(UIFont *))aozFont;
- (UITextView * (^)(UIEdgeInsets))aozTextContainerInset;
- (UITextView * (^)(NSAttributedString *))aozAttributedText;
- (UITextView * (^)(NSDictionary<NSString *,id> *))aozTypingAttributes;
- (UITextView * (^)(UIDataDetectorTypes))aozDataDetectorTypes;
- (UITextView * (^)(BOOL))aozAllowsEditingTextAttributes;
- (UITextView * (^)(UIColor *))aozTextColor;
- (UITextView * (^)(NSDictionary<NSString *,id> *))aozLinkTextAttributes;
- (UITextView * (^)(NSTextAlignment))aozTextAlignment;

#pragma mark Selection
- (UITextView * (^)(BOOL))aozSelectable;
- (UITextView * (^)(BOOL))aozClearsOnInsertion;
- (UITextView * (^)(NSRange))aozSelectedRange;

#pragma mark Delegate
- (UITextView * (^)(id<UITextViewDelegate>))aozDelegate;

#pragma mark System Input Views
- (UITextView * (^)(UIView *))aozInputView;
- (UITextView * (^)(UIView *))aozInputAccessoryView;

#pragma mark Delegate

#pragma mark Display of Content
- (UITextView * (^)(CGPoint))aozContentOffset;
- (UITextView * (^)(UIEdgeInsets))aozContentInset;
- (UITextView * (^)(CGSize))aozContentSize;

#pragma mark Managing Scrolling
- (UITextView * (^)(CGFloat))aozDecelerationRate;
- (UITextView * (^)(BOOL))aozPagingEnabled;
- (UITextView * (^)(BOOL))aozScrollEnabled;
- (UITextView * (^)(BOOL))aozDelaysContentTouches;
- (UITextView * (^)(BOOL))aozAlwaysBounceHorizontal;
- (UITextView * (^)(BOOL))aozDirectionalLockEnabled;
- (UITextView * (^)(BOOL))aozScrollsToTop;
- (UITextView * (^)(BOOL))aozCanCancelContentTouches;
- (UITextView * (^)(BOOL))aozBounces;
- (UITextView * (^)(BOOL))aozAlwaysBounceVertical;

#pragma mark Scroll Indicator 
- (UITextView * (^)(UIScrollViewIndicatorStyle))aozIndicatorStyle;
- (UITextView * (^)(BOOL))aozShowsVerticalScrollIndicator;
- (UITextView * (^)(UIEdgeInsets))aozScrollIndicatorInsets;
- (UITextView * (^)(BOOL))aozShowsHorizontalScrollIndicator;

#pragma mark Zooming and Panning
- (UITextView * (^)(CGFloat))aozZoomScale;
- (UITextView * (^)(BOOL))aozBouncesZoom;
- (UITextView * (^)(CGFloat))aozMaximumZoomScale;
- (UITextView * (^)(CGFloat))aozMinimumZoomScale;

#pragma mark Keyboard and Index
- (UITextView * (^)(UIScrollViewIndexDisplayMode))aozIndexDisplayMode;
- (UITextView * (^)(UIScrollViewKeyboardDismissMode))aozKeyboardDismissMode;

#pragma mark Superviews
- (UITextView * (^)(UIView *))aozAddToSuperview;

#pragma mark Layers
- (UITextView * (^)(UIColor *))aozLayerBorderColor;
- (UITextView * (^)(CGFloat))aozLayerBorderWidth;
- (UITextView * (^)(CGFloat))aozLayerCornerRaduis;

#pragma mark Bounds and Frames
- (UITextView * (^)(CGRect))aozFrame;
- (UITextView * (^)(CGAffineTransform))aozTransform;
- (UITextView * (^)(CGRect))aozBounds;
- (UITextView * (^)(CGPoint))aozCenter;

#pragma mark Visual Appearance
- (UITextView * (^)(BOOL))aozClipsToBounds;
- (UITextView * (^)(BOOL))aozOpaque;
- (UITextView * (^)(UIColor *))aozTintColor;
- (UITextView * (^)(UIViewTintAdjustmentMode))aozTintAdjustmentMode;
- (UITextView * (^)(UIColor *))aozBackgroundColor;
- (UITextView * (^)(CGFloat))aozAlpha;
- (UITextView * (^)(BOOL))aozHidden;

#pragma mark Events
- (UITextView * (^)(BOOL))aozUserInteractionEnabled;
- (UITextView * (^)(BOOL))aozExclusiveTouch;
- (UITextView * (^)(BOOL))aozMultipleTouchEnabled;

#pragma mark Resizing Behavior
- (UITextView * (^)(UIViewContentMode))aozContentMode;

#pragma mark Identifying the View at Runtime
- (UITextView * (^)(NSInteger))aozTag;

@end
