//
//  UIView+AOZCategory.h
//  AOZKit
//
//  Auto generated by Aozorany.
//  DO NOT EDIT THIS FILE DIRECTLY, IF YOU HAVE NEW CLASSES OR PROPERTIES, PLEASE ADD THEM TO AOZCategorygGenerator.py!


#import <UIKit/UIKit.h>


@interface UIView (AOZCategory)

#pragma mark Superviews
- (UIView * (^)(UIView *))aozAddToSuperview;

#pragma mark Layers
- (UIView * (^)(UIColor *))aozLayerBorderColor;
- (UIView * (^)(CGFloat))aozLayerBorderWidth;
- (UIView * (^)(CGFloat))aozLayerCornerRaduis;

#pragma mark Bounds and Frames
- (UIView * (^)(CGRect))aozFrame;
- (UIView * (^)(CGAffineTransform))aozTransform;
- (UIView * (^)(CGRect))aozBounds;
- (UIView * (^)(CGPoint))aozCenter;

#pragma mark Visual Appearance
- (UIView * (^)(BOOL))aozClipsToBounds;
- (UIView * (^)(BOOL))aozOpaque;
- (UIView * (^)(UIColor *))aozTintColor;
- (UIView * (^)(UIViewTintAdjustmentMode))aozTintAdjustmentMode;
- (UIView * (^)(UIColor *))aozBackgroundColor;
- (UIView * (^)(CGFloat))aozAlpha;
- (UIView * (^)(BOOL))aozHidden;

#pragma mark Events
- (UIView * (^)(BOOL))aozUserInteractionEnabled;
- (UIView * (^)(BOOL))aozExclusiveTouch;
- (UIView * (^)(BOOL))aozMultipleTouchEnabled;

#pragma mark Resizing Behavior
- (UIView * (^)(UIViewContentMode))aozContentMode;

#pragma mark Identifying the View at Runtime
- (UIView * (^)(NSInteger))aozTag;

@end
